/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   ShrubberyCreationForm.cpp                         :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: user <marvin@42.fr>                        +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2021/09/15 19:39:10 by user              #+#    #+#             */
/*   Updated: 2021/09/20 14:35:50 by edassess         ###   ########lyon.fr   */
/*                                                                            */
/* ************************************************************************** */

#include "ShrubberyCreationForm.hpp"

ShrubberyCreationForm::ShrubberyCreationForm(std::string target) : _target(target), Form("ShrubberyCreationForm", 5, 25)
{
	return;
}

ShrubberyCreationForm::ShrubberyCreationForm(ShrubberyCreationForm const &rhs) : _target(rhs._target), Form(rhs.getName(), rhs.getToSign(), rhs.getToExecute())
{
	*this = rhs;
	return;
}

ShrubberyCreationForm::~ShrubberyCreationForm(void)
{
	return;
}

void	ShrubberyCreationForm::action(void)const
{
	std::cout << "Creating " << this->_target << "_shrubbery..." << std::endl;
	std::ofstream ofs(this->_target + "_shrubbery");
	ofs << "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMWkcONWMMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\nMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNWk.,o0NO0WMWKk0WMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\nMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMMMMMWWMKc;dKkx00o:OWXd'.dNXNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\nMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXkOWMMMKdkNNx..cXWNXKK0Xk,,dXO;oXXNMMMMWXkx0WMMMMMMMMMMMMMMMMMMMMMMM\nMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXo.;KWWMO'.lXWOcoKXKN0:'kKdOWMk.cOc;xNWNx'.:OWMMMMMMMMMMMMMMMMMMMMMMM\nMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWXc.lOoldOd',ONo,kX0OKo.cKx.c0kOOKK:..xWXxoxKXNWWWMMMMMMMMMMMMMMMMMMMM\nMMMMMMMMMMMMMMMMMMMWMWWWMMMNx:lOOkKXxoldKOd0K:.dKkkK0dKWd,xd.:KWWO;.lKOl:',oKWWMWMMMMMMMMMMMMMMMMMMM\nMMMMMMMMMMMMMMMMMMWWMOldKWNNKl''xKx:l0XXOc;coooKOdkko,dWNOxo,,ON0XXdxkc;c;:0WMXxkNWMMMMMMMMMMMMMMMMM\nMMMMMMMMMMMMMMMMMMMWW0,.;xo:coxxkxocc:,dKklcoodKk:c,..lNNl,kKOk:,kKx0WNNK:.lNWx..kWWWWMMMMMMMMMMMMMM\nMMMMMMMMMMMMMMMMMW0dkKOc,oO:...oOOKc.'oXKl:oOXdcc''..,dKNOONNKl;kNxdX0dkk,.:KWk.'OWNWMMMMMMMMMMMMMMM\nMMMMMMMMMMMMMMMMWWx..,xXXXX0kl::oxOxoxONXc...lk:.oOolkc:0Xock00ddkldo,cOKo;kWMNOkklcOWMMMMMMMMMMMMMM\nMMMMMMMMMMMMMMWX0KO;...xNKc;kNWN0ok0:.l0Oo'...lc'kWNKKxckNO;lkx,.,:kOol:lOKxxXWKo..cKMMMMMMMMMMMMMMM\nMMMMMMMMMMMMMMWO;':o;..lNx..;0WWWdloclc,.lk:..c:,xOo'oKxkkockkoc,';xc..:kNk'.o0OolkXNNMMMMMMMMMMMMMM\nMMMMMMMMMMMWWNXKOdcd0olOWk'.:KKoxk:d0c..;kXNxox;;l,..coc;..cK0ok0:;xd:;xWXkc.;xKKxl::OWMMMMMMMMMMMMM\nMMMMMMMMWWKdc;,',dOkxkOkkkoo0Nd..::;l::ol,oWWWk':xolcclc;lolx0od0;:k:.:OWOOXdckd,.':xNMMMMMMMMMMMMMM\nMMMMMMMMWO:..';clc,.,xKxc:co0Nx...c:'dXx..:oOWd.cXWKclX0OOkc.::cd'cOxddKKd0KldKdoOKNWMMMMMMMMMMMMMMM\nMMMMMMMMWNK0KXNXl..:O0dclxOd:cdo;.l0:'lolkl.'ko.cKXl;do,..lOkxo,..oWNl.ldoxcoXx.:XWWWMMMMMMMMMMMMMMM\nMMMMMMMMMMMMMMMNxd0NWWWXOxxxo;';clOWKc.;xKk'.cc.:o;,:,..,ol,dNO, 'x00o;l;,;lk0l.cdllKWWMMMMMMMMMMMMM\nMMMMMMMMMMMMMMMMWWWWOlxOl,...'::'.,:l:...,l:;xc... ;o;;dKO,.;0x..;c;xKx;.;kk,;xkl,,l0NMMMMMMMMMMMMMM\nMMMMMMMMMMMMMMMWNXNW0,.OWXOdc;;:'............,'... cKOkXWXl.oO;.'ol:c;.':cdd,;OKo,';dNMMMMMMMMMMMMMM\nMMMMMMMMMMMMMMNO:,,:oddOkol:;:l:,:ool:;;,......... cOc.oWMXkl'...'...'oo::xkox0kc:o0WMMMMMMMMMMMMMMM\nMMMMMMMMMMMMMMWKxlloodkxdl;':xo,.dKo:,c0X0koc,.... ,l'.xN0o,.....',,,;cccdodxl;...':xNMMMMMMMMMMMMMM\nMMMMMMMMMMMMMXo,',:dxxKNd..,dc..'d:..c0WWMWWWKd'....;lxOc....'cx0XXXXXKKXNOl;;cooodkKWMMMMMMMMMMMMMM\nMMMMMMMMMMMMMN0kxlx0c.dXl;oKX:.'x0lcONWMMMMMMMWk'....;o,...;xXWWMMMMMMMMMMWXOk0NMMMMMMMMMMMMMMMMMMMM\nMMMMMMMMMMMMMMM0:.lO,.cXNNMMW0dOWWWWMMWMMMMMMMMWd.........lXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\nMMMMMMMMMMMMMMWd.'kNd:OWMMMMMMMMMMMMMMMMMMMMMMMMX:.......cXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\nMMMMMMMMMMMMMMW0d0WMWNWMMMMMMMMMMMMMMMMMMMMMMMMMWx,......xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\nMMMMMMMMMMMMMMMMMMMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMOl,....'OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\nMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0d;....'OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\nMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKd;....'OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\nMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0d;....'kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\nMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMOl,.....kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\nMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk,......xMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\nMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWo.......xMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\nMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXc.......oXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\nMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMMMNXK0OOkkkxdc.........':lxKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\nMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWKxl;'...........',,..,odl:'.'ckXWWNKOxddxk0NMMMMMMMMMMMMMMMMMMMMMM\nMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMWXo'.,okd,.,okOl.'xKX0;.,d0XN0o;..,::::::,,cooodkXWWWWWWMMMMMMMMMMMMM\nMMMMMMMMMMMMMMMMMMMMMMMMWWWX00ko,.lxkNXl.cKWWXl.'kWWNo....cxO0XO:.'o0XNWXOdONNx;lkOXMMMWMMMMMMMMMMMM\nMMMMMMMMMMMMMMMMMMMMMMMWNXK0Okc.'xNKKW0,;KMN0dd:.dWWWXd:lc,:dO0NNo.cXMWWMMN0OXNkx0OO0KXNWWMMMMMMMMMM\nMMMMMMMMMMMMMMMMMMMNKOkxdoooooldKWWXKOc.oNK00XXc.kWMMMWkd0O;;OKXMK;.xWWWMMMWNXNN0ONWWNXNNWMMMMMMMMMM\nMMMMMMMMMMMMMMMWNK00OOkoldk0KXWWNXK0kc,cKNXWW0l':KMMMMWNk0Wd.oWWWk,,;kNWMMWMMMMMWXXNWWMMMMMMMMMMMMMM\nMMMMMMMMMMMMMMWNXXWWWNOkNWMWMMWWNNKxc;dNWWMNx:okdOMMWWMWX0xc'oWMWooKdcokKNWMMMMMMMWWWMMWMMMMMMMMMMMM\nMMMMMMMMMMMMMMWWMMMMMN0XMMMMMMMMXxdxdkNMMMWo,xWXOKMMWMMMXxk0cdMMWkdNMXd:lkkONMMMMMMMMMMMMMMMMMMMMMMM\nMMMMMMMMMMMMMMMMMMMMMWXNMMMMMMMXxONN0KWWMMO::0WXXWMMMMMMKOXKcdWMMNOONWWKO0OOk0WMMMMMMMMMMMMMMMMMMMMM\nMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWOOWMMNNWMMMkdkONWMMMMMMMMNXWKodKNWMWXNNWMWXKNN0KMMMMMMMMMMMMMMMMMMMMM\nMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKXMMMMMMMMMOkXKXMMMMMMMMMMWMNkONNWWMMMMWMMMWWWNXWMMMMMMMMMMMMMMMMMMMM\nMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNMMMMMMMMMN0KNWMMMMMMMMMMMMMX0XWMMMMMMMMMMMMMWMMMMMMMMMMMMMMMMMMMMMM\nMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNXWMMMMMMMMMMMMMMMWNNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\nMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM";
	ofs.close();
}
